### ISSUE TITLE
Proj-6 bug

### ISSUE THREAD

**Issue by andersp** [geodynamics/sw4#109]
There is a bug in parseInputFile.C on line 1268 where the undefined variable ENABLE_PROJ_NEW is used. Should be ENABLE_PROJ_6. @houjun can you fix this?

**Comment by houjun** [comment]
@andersp I fixed that in the last pull request #108, maybe your local copy is before that?
[latest developer branch](https://github.com/geodynamics/sw4/blob/developer/src/parseInputFile.C#L1268)

**Comment by andersp** [comment]
I just pulled from the developer branch. Are you sure you pushed it?

**Comment by houjun** [comment]
yes, if you click the [link](https://github.com/geodynamics/sw4/blob/developer/src/parseInputFile.C#L1268) it shows the correct variable is used:
#if !defined(ENABLE_PROJ4) && !defined(ENABLE_PROJ_6)

**Comment by andersp** [comment]
My mistake. I only pulled on my laptop, not on quartz. I will rebuild and rerun the test.

**Comment by andersp** [comment]
The code still crashes if there is no fileio command in the input file. But it works if you add the line
fileio path=.
The output directory should default to "." if there is no fileio command.

**Comment by houjun** [comment]
should be fixed with #110
